//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace src.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("src.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Edge.
        /// </summary>
        internal static string BtnAddEdge {
            get {
                return ResourceManager.GetString("BtnAddEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Node.
        /// </summary>
        internal static string BtnAddNode {
            get {
                return ResourceManager.GetString("BtnAddNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string BtnClear {
            get {
                return ResourceManager.GetString("BtnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creat.
        /// </summary>
        internal static string BtnCreat {
            get {
                return ResourceManager.GetString("BtnCreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Edge.
        /// </summary>
        internal static string BtnEditEdge {
            get {
                return ResourceManager.GetString("BtnEditEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase Edge.
        /// </summary>
        internal static string BtnEraseEdge {
            get {
                return ResourceManager.GetString("BtnEraseEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase Node.
        /// </summary>
        internal static string BtnEraseNode {
            get {
                return ResourceManager.GetString("BtnEraseNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Input.
        /// </summary>
        internal static string BtnHideInput {
            get {
                return ResourceManager.GetString("BtnHideInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string BtnRun {
            get {
                return ResourceManager.GetString("BtnRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string BtnSelect {
            get {
                return ResourceManager.GetString("BtnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sink(s).
        /// </summary>
        internal static string BtnSelectSink {
            get {
                return ResourceManager.GetString("BtnSelectSink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Source(s).
        /// </summary>
        internal static string BtnSelectSource {
            get {
                return ResourceManager.GetString("BtnSelectSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Input.
        /// </summary>
        internal static string BtnShowInput {
            get {
                return ResourceManager.GetString("BtnShowInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Test Case:.
        /// </summary>
        internal static string LabelChooseTest {
            get {
                return ResourceManager.GetString("LabelChooseTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand.
        /// </summary>
        internal static string LabelDemand {
            get {
                return ResourceManager.GetString("LabelDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT.
        /// </summary>
        internal static string LabelInput {
            get {
                return ResourceManager.GetString("LabelInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Flow: ---.
        /// </summary>
        internal static string LabelMaxFlow {
            get {
                return ResourceManager.GetString("LabelMaxFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply.
        /// </summary>
        internal static string LabelSupply {
            get {
                return ResourceManager.GetString("LabelSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can move the nodes to make them easier to see....
        /// </summary>
        internal static string MsgMoveNode {
            get {
                return ResourceManager.GetString("MsgMoveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Flow Simulator.
        /// </summary>
        internal static string NavMaxFlowSimulator {
            get {
                return ResourceManager.GetString("NavMaxFlowSimulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation Problem.
        /// </summary>
        internal static string NavTransportation {
            get {
                return ResourceManager.GetString("NavTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic supply/demand banlance.
        /// </summary>
        internal static string OptionAutoBanlance {
            get {
                return ResourceManager.GetString("OptionAutoBanlance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color by Flow.
        /// </summary>
        internal static string OptionColorByFlow {
            get {
                return ResourceManager.GetString("OptionColorByFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Animation.
        /// </summary>
        internal static string OptionEnableAimation {
            get {
                return ResourceManager.GetString("OptionEnableAimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are a team of students passionate about applying Discrete Mathematics 
        ///to practical problems. This project focuses on visualizing 
        ///the Edmonds-Karp (Max Flow) algorithm, allowing users to 
        ///easily input data, view results, and understand how network flow 
        ///theory works in practice.
        ///
        ///The application also demonstrates real-life uses of maximum flow, such as in transportation, 
        ///logistics, and communication networks, making abstract concepts more accessible and engaging.
        ///.
        /// </summary>
        internal static string TextAbout {
            get {
                return ResourceManager.GetString("TextAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string titleAboutUs {
            get {
                return ResourceManager.GetString("titleAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example : 50,40,5.
        /// </summary>
        internal static string TitleExample1 {
            get {
                return ResourceManager.GetString("TitleExample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example :20,10,60.
        /// </summary>
        internal static string TitleExample2 {
            get {
                return ResourceManager.GetString("TitleExample2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a non-negative interger..
        /// </summary>
        internal static string TitleExample3 {
            get {
                return ResourceManager.GetString("TitleExample3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUP 11.
        /// </summary>
        internal static string TitleGroup11 {
            get {
                return ResourceManager.GetString("TitleGroup11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Flow = --.
        /// </summary>
        internal static string TitleMaxFlow {
            get {
                return ResourceManager.GetString("TitleMaxFlow", resourceCulture);
            }
        }
    }
}
